---
title: "SAFE examples - apartments dataset"
author: "Anna Gierlak"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(SAFE)
library(DALEX)
# library(changepoint.np)
# library(strucchange)
library(randomForest)
# library(ggplot2)
library(gridExtra)
library(dplyr)
# library(utils)
# library(stringr)
# library(iml)
# library(factorMerger)
```

Models fitted to the original dataset - linear model and random forest:

```{r, warning = FALSE}
model_lm1 <- lm(m2.price ~ ., data = apartments)
explainer_lm1 <- explain(model_lm1, data = apartmentsTest[1:3000,2:6], y = apartmentsTest[1:3000,1], label = "lm1")
set.seed(111)
model_rf1 <- randomForest(m2.price ~ ., data = apartments)
explainer_rf1 <- explain(model_rf1, data = apartmentsTest[1:3000,2:6], y = apartmentsTest[1:3000,1], label = "rf1")
```


Creating safe_extractor object using SAFE package:

```{r, warning = FALSE}
apartments_safer <- safer(explainer_rf1)
```

```{r, warning = FALSE}
print(apartments_safer)
```

```{r, fig.width=6, warning = FALSE}
plot(apartments_safer, "construction.year")
```

Using created object to extract new features:

```{r, fig.width=6, warning = FALSE}
data1 <- transform_data(apartmentsTest[3001:6000,], apartments_safer)
```

```{r, echo = FALSE}
knitr::kable(head(data1))
```

The same with one-hot encoding:

```{r, fig.width=6, warning = FALSE}
data1 <- transform_data(apartmentsTest[3001:6000,], apartments_safer, encoding = "one-hot")
```

Backward feature selection:

```{r, fig.width=6, warning = FALSE}
model_selection <- lm(m2.price ~ ., data = data1)
sel <- stats::step(model_selection, direction = 'backward')
data1 <- data1[,c(attr(sel$terms, "term.labels"), "m2.price")]
```

```{r, echo = FALSE}
knitr::kable(head(data1))
```

Data for exaplainers:

```{r, fig.width=6, warning = FALSE}
data2 <- transform_data(apartmentsTest[6001:9000,], apartments_safer, encoding = "one-hot")
data2 <- data2[,c(attr(sel$terms, "term.labels"), "m2.price")]
```




Fitting models to data containg newly created columns:

```{r, warning = FALSE}
model_lm2 <- lm(m2.price ~ ., data = data1)
explainer_lm2 <- explain(model_lm2, data = data2, y = apartmentsTest[6001:9000,1], label = "lm2")

set.seed(111)
model_rf2 <- randomForest(m2.price ~ ., data = data1)
explainer_rf2 <- explain(model_rf2, data2, apartmentsTest[6001:9000,1], label = "rf2")
```


```{r, echo = FALSE, warning = FALSE}
mp_lm1 <- model_performance(explainer_lm1)
vi_lm1 <- variable_importance(explainer_lm1, type = "difference")

mp_rf1 <- model_performance(explainer_rf1)
vi_rf1 <- variable_importance(explainer_rf1, type = "difference")

mp_lm2 <- model_performance(explainer_lm2)
vi_lm2 <- variable_importance(explainer_lm2, type = "difference")

mp_rf2 <- model_performance(explainer_rf2)
vi_rf2 <- variable_importance(explainer_rf2, type = "difference")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
plot(mp_lm1, mp_rf1, mp_lm2, mp_rf2, geom = "boxplot")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
grid.arrange(
  plot(vi_lm1, vi_lm2),
  plot(vi_rf1, vi_rf2), ncol = 2)
```

```{r}
summary(model_lm1)
summary(model_lm2)
```

