---
title: "SAFE examples - apartments dataset"
author: "Anna Gierlak"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(SAFE)
library(DALEX)
library(changepoint.np)
library(strucchange)
library(randomForest)
library(ggplot2)
library(gridExtra)
library(utils)
library(stringr)
library(iml)
library(factorMerger)
```

Modele oparte na oryginalnych danych:

```{r, warning = FALSE}
model_lm1 <- lm(m2.price ~ ., data = apartments)
explainer_lm1 <- explain(model_lm1, data = apartmentsTest[1:3000,2:6], y = apartmentsTest[1:3000,1], label = "lm1")
set.seed(111)
model_rf1 <- randomForest(m2.price ~ ., data = apartments)
explainer_rf1 <- explain(model_rf1, data = apartmentsTest[1:3000,2:6], y = apartmentsTest[1:3000,1], label = "rf1")
```


**Transformacje (package=changepoint.np, type=constant):**

```{r, fig.width=6, warning = FALSE}
trans_prop <- transform_propositions(explainer_rf1, package = "changepoint.np", type = "constant", plot = TRUE)

data1_new <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "only_new")
data1_all <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "all")
data1_aic <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "aic")

data1_new <- cbind(apartmentsTest[3001:6000,1], data1_new)
colnames(data1_new)[1] <- 'm2.price'
data1_all <- cbind(apartmentsTest[3001:6000,1], data1_all)
colnames(data1_all)[1] <- 'm2.price'
data1_aic <- cbind(apartmentsTest[3001:6000,1], data1_aic)
colnames(data1_aic)[1] <- 'm2.price'
```

```{r, echo = FALSE}
knitr::kable(head(data1_all))
```

```{r, warning = FALSE}
data2_new <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "only_new")
data2_all <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "all")
data2_aic <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "all")
data2_aic <- data2_aic[,names(data2_aic) %in% names(data1_aic)]

model_lm2_new <- lm(m2.price ~ ., data = data1_new)
explainer_lm2_new <- explain(model_lm2_new, data = data2_new, y = apartmentsTest[6001:9000,1], label = "lm2_new")

model_lm2_all <- lm(m2.price ~ ., data = data1_all)
explainer_lm2_all <- explain(model_lm2_all, data = data2_all, y = apartmentsTest[6001:9000,1], label = "lm2_all")

model_lm2_aic <- lm(m2.price ~ ., data = data1_aic)
explainer_lm2_aic <- explain(model_lm2_aic, data = data2_aic, y = apartmentsTest[6001:9000,1], label = "lm2_aic")

set.seed(111)
model_rf2_new <- randomForest(m2.price ~ ., data = data1_new)
explainer_rf2_new <- explain(model_rf2_new, data2_new, apartmentsTest[6001:9000,1], label = "rf2_new")

set.seed(111)
model_rf2_all <- randomForest(m2.price ~ ., data = data1_all)
explainer_rf2_all <- explain(model_rf2_all, data2_all, apartmentsTest[6001:9000,1], label = "rf2_all")

set.seed(111)
model_rf2_aic <- randomForest(m2.price ~ ., data = data1_aic)
explainer_rf2_aic <- explain(model_rf2_aic, data2_aic, apartmentsTest[6001:9000,1], label = "rf2_aic")
```

```{r, echo = FALSE, warning = FALSE}
mp_lm1 <- model_performance(explainer_lm1)
vi_lm1 <- variable_importance(explainer_lm1, type = "difference")

mp_rf1 <- model_performance(explainer_rf1)
vi_rf1 <- variable_importance(explainer_rf1, type = "difference")

mp_lm2_new <- model_performance(explainer_lm2_new)
vi_lm2_new <- variable_importance(explainer_lm2_new, type = "difference")

mp_lm2_all <- model_performance(explainer_lm2_all)
vi_lm2_all <- variable_importance(explainer_lm2_all, type = "difference")

mp_lm2_aic <- model_performance(explainer_lm2_aic)
vi_lm2_aic <- variable_importance(explainer_lm2_aic, type = "difference")

mp_rf2_new <- model_performance(explainer_rf2_new)
vi_rf2_new <- variable_importance(explainer_rf2_new, type = "difference")

mp_rf2_all <- model_performance(explainer_rf2_all)
vi_rf2_all <- variable_importance(explainer_rf2_all, type = "difference")

mp_rf2_aic <- model_performance(explainer_rf2_aic)
vi_rf2_aic <- variable_importance(explainer_rf2_aic, type = "difference")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
plot(mp_lm1, mp_rf1, mp_lm2_new, mp_lm2_all, mp_lm2_aic, mp_rf2_new, mp_rf2_all, mp_rf2_aic, geom = "boxplot")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
grid.arrange(
  plot(vi_lm1, vi_lm2_new, vi_lm2_all, vi_lm2_aic),
  plot(vi_rf1, vi_rf2_new, vi_rf2_all, vi_rf2_aic), ncol = 2)
```

```{r}
summary(model_lm1)
summary(model_lm2_aic)
```





**Transformacje (package=strucchange, type=constant):**

```{r, fig.width=6, warning = FALSE}
trans_prop <- transform_propositions(explainer_rf1, package = "strucchange", type = "constant", plot = TRUE)

data1_new <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "only_new")
data1_all <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "all")
data1_aic <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "aic")

data1_new <- cbind(apartmentsTest[3001:6000,1], data1_new)
colnames(data1_new)[1] <- 'm2.price'
data1_all <- cbind(apartmentsTest[3001:6000,1], data1_all)
colnames(data1_all)[1] <- 'm2.price'
data1_aic <- cbind(apartmentsTest[3001:6000,1], data1_aic)
colnames(data1_aic)[1] <- 'm2.price'
```

```{r, echo = FALSE}
knitr::kable(head(data1_all))
```

```{r, warning = FALSE}
data2_new <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "only_new")
data2_all <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "all")
data2_aic <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "all")
data2_aic <- data2_aic[,names(data2_aic) %in% names(data1_aic)]

model_lm2_new <- lm(m2.price ~ ., data = data1_new)
explainer_lm2_new <- explain(model_lm2_new, data = data2_new, y = apartmentsTest[6001:9000,1], label = "lm2_new")

model_lm2_all <- lm(m2.price ~ ., data = data1_all)
explainer_lm2_all <- explain(model_lm2_all, data = data2_all, y = apartmentsTest[6001:9000,1], label = "lm2_all")

model_lm2_aic <- lm(m2.price ~ ., data = data1_aic)
explainer_lm2_aic <- explain(model_lm2_aic, data = data2_aic, y = apartmentsTest[6001:9000,1], label = "lm2_aic")

set.seed(111)
model_rf2_new <- randomForest(m2.price ~ ., data = data1_new)
explainer_rf2_new <- explain(model_rf2_new, data2_new, apartmentsTest[6001:9000,1], label = "rf2_new")

set.seed(111)
model_rf2_all <- randomForest(m2.price ~ ., data = data1_all)
explainer_rf2_all <- explain(model_rf2_all, data2_all, apartmentsTest[6001:9000,1], label = "rf2_all")

set.seed(111)
model_rf2_aic <- randomForest(m2.price ~ ., data = data1_aic)
explainer_rf2_aic <- explain(model_rf2_aic, data2_aic, apartmentsTest[6001:9000,1], label = "rf2_aic")
```

```{r, echo = FALSE, warning = FALSE}
mp_lm1 <- model_performance(explainer_lm1)
vi_lm1 <- variable_importance(explainer_lm1, type = "difference")

mp_rf1 <- model_performance(explainer_rf1)
vi_rf1 <- variable_importance(explainer_rf1, type = "difference")

mp_lm2_new <- model_performance(explainer_lm2_new)
vi_lm2_new <- variable_importance(explainer_lm2_new, type = "difference")

mp_lm2_all <- model_performance(explainer_lm2_all)
vi_lm2_all <- variable_importance(explainer_lm2_all, type = "difference")

mp_lm2_aic <- model_performance(explainer_lm2_aic)
vi_lm2_aic <- variable_importance(explainer_lm2_aic, type = "difference")

mp_rf2_new <- model_performance(explainer_rf2_new)
vi_rf2_new <- variable_importance(explainer_rf2_new, type = "difference")

mp_rf2_all <- model_performance(explainer_rf2_all)
vi_rf2_all <- variable_importance(explainer_rf2_all, type = "difference")

mp_rf2_aic <- model_performance(explainer_rf2_aic)
vi_rf2_aic <- variable_importance(explainer_rf2_aic, type = "difference")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
plot(mp_lm1, mp_rf1, mp_lm2_new, mp_lm2_all, mp_lm2_aic, mp_rf2_new, mp_rf2_all, mp_rf2_aic, geom = "boxplot")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
grid.arrange(
  plot(vi_lm1, vi_lm2_new, vi_lm2_all, vi_lm2_aic),
  plot(vi_rf1, vi_rf2_new, vi_rf2_all, vi_rf2_aic), ncol = 2)
```

```{r}
summary(model_lm1)
summary(model_lm2_aic)
```




**Transformacje (package=changepoint.np, type=linear):**

```{r, fig.width=6, warning = FALSE}
trans_prop <- transform_propositions(explainer_rf1, package = "changepoint.np", type = "linear", plot = TRUE)

data1_new <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "only_new")
data1_all <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "all")
data1_aic <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "aic")

data1_new <- cbind(apartmentsTest[3001:6000,1], data1_new)
colnames(data1_new)[1] <- 'm2.price'
data1_all <- cbind(apartmentsTest[3001:6000,1], data1_all)
colnames(data1_all)[1] <- 'm2.price'
data1_aic <- cbind(apartmentsTest[3001:6000,1], data1_aic)
colnames(data1_aic)[1] <- 'm2.price'
```

```{r, echo = FALSE}
knitr::kable(head(data1_all))
```

```{r, warning = FALSE}
data2_new <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "only_new")
data2_all <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "all")
data2_aic <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "all")
data2_aic <- data2_aic[,names(data2_aic) %in% names(data1_aic)]

model_lm2_new <- lm(m2.price ~ ., data = data1_new)
explainer_lm2_new <- explain(model_lm2_new, data = data2_new, y = apartmentsTest[6001:9000,1], label = "lm2_new")

model_lm2_all <- lm(m2.price ~ ., data = data1_all)
explainer_lm2_all <- explain(model_lm2_all, data = data2_all, y = apartmentsTest[6001:9000,1], label = "lm2_all")

model_lm2_aic <- lm(m2.price ~ ., data = data1_aic)
explainer_lm2_aic <- explain(model_lm2_aic, data = data2_aic, y = apartmentsTest[6001:9000,1], label = "lm2_aic")

set.seed(111)
model_rf2_new <- randomForest(m2.price ~ ., data = data1_new)
explainer_rf2_new <- explain(model_rf2_new, data2_new, apartmentsTest[6001:9000,1], label = "rf2_new")

set.seed(111)
model_rf2_all <- randomForest(m2.price ~ ., data = data1_all)
explainer_rf2_all <- explain(model_rf2_all, data2_all, apartmentsTest[6001:9000,1], label = "rf2_all")

set.seed(111)
model_rf2_aic <- randomForest(m2.price ~ ., data = data1_aic)
explainer_rf2_aic <- explain(model_rf2_aic, data2_aic, apartmentsTest[6001:9000,1], label = "rf2_aic")
```

```{r, echo = FALSE, warning = FALSE}
mp_lm1 <- model_performance(explainer_lm1)
vi_lm1 <- variable_importance(explainer_lm1, type = "difference")

mp_rf1 <- model_performance(explainer_rf1)
vi_rf1 <- variable_importance(explainer_rf1, type = "difference")

mp_lm2_new <- model_performance(explainer_lm2_new)
vi_lm2_new <- variable_importance(explainer_lm2_new, type = "difference")

mp_lm2_all <- model_performance(explainer_lm2_all)
vi_lm2_all <- variable_importance(explainer_lm2_all, type = "difference")

mp_lm2_aic <- model_performance(explainer_lm2_aic)
vi_lm2_aic <- variable_importance(explainer_lm2_aic, type = "difference")

mp_rf2_new <- model_performance(explainer_rf2_new)
vi_rf2_new <- variable_importance(explainer_rf2_new, type = "difference")

mp_rf2_all <- model_performance(explainer_rf2_all)
vi_rf2_all <- variable_importance(explainer_rf2_all, type = "difference")

mp_rf2_aic <- model_performance(explainer_rf2_aic)
vi_rf2_aic <- variable_importance(explainer_rf2_aic, type = "difference")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
plot(mp_lm1, mp_rf1, mp_lm2_new, mp_lm2_all, mp_lm2_aic, mp_rf2_new, mp_rf2_all, mp_rf2_aic, geom = "boxplot")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
grid.arrange(
  plot(vi_lm1, vi_lm2_new, vi_lm2_all, vi_lm2_aic),
  plot(vi_rf1, vi_rf2_new, vi_rf2_all, vi_rf2_aic), ncol = 2)
```

```{r}
summary(model_lm1)
summary(model_lm2_aic)
```






**Transformacje (package=strucchange, type=linear):**

```{r, fig.width=6, warning = FALSE}
trans_prop <- transform_propositions(explainer_rf1, package = "strucchange", type = "linear", plot = TRUE)

data1_new <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "only_new")
data1_all <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "all")
data1_aic <- transform_data(apartmentsTest[3001:6000,2:6], apartmentsTest[3001:6000,1], trans_prop, which_variables = "aic")

data1_new <- cbind(apartmentsTest[3001:6000,1], data1_new)
colnames(data1_new)[1] <- 'm2.price'
data1_all <- cbind(apartmentsTest[3001:6000,1], data1_all)
colnames(data1_all)[1] <- 'm2.price'
data1_aic <- cbind(apartmentsTest[3001:6000,1], data1_aic)
colnames(data1_aic)[1] <- 'm2.price'
```

```{r, echo = FALSE}
knitr::kable(head(data1_all))
```

```{r, warning = FALSE}
data2_new <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "only_new")
data2_all <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "all")
data2_aic <- transform_data(apartmentsTest[6001:9000,2:6], apartmentsTest[6001:9000,1], trans_prop, which_variables = "all")
data2_aic <- data2_aic[,names(data2_aic) %in% names(data1_aic)]

model_lm2_new <- lm(m2.price ~ ., data = data1_new)
explainer_lm2_new <- explain(model_lm2_new, data = data2_new, y = apartmentsTest[6001:9000,1], label = "lm2_new")

model_lm2_all <- lm(m2.price ~ ., data = data1_all)
explainer_lm2_all <- explain(model_lm2_all, data = data2_all, y = apartmentsTest[6001:9000,1], label = "lm2_all")

model_lm2_aic <- lm(m2.price ~ ., data = data1_aic)
explainer_lm2_aic <- explain(model_lm2_aic, data = data2_aic, y = apartmentsTest[6001:9000,1], label = "lm2_aic")

set.seed(111)
model_rf2_new <- randomForest(m2.price ~ ., data = data1_new)
explainer_rf2_new <- explain(model_rf2_new, data2_new, apartmentsTest[6001:9000,1], label = "rf2_new")

set.seed(111)
model_rf2_all <- randomForest(m2.price ~ ., data = data1_all)
explainer_rf2_all <- explain(model_rf2_all, data2_all, apartmentsTest[6001:9000,1], label = "rf2_all")

set.seed(111)
model_rf2_aic <- randomForest(m2.price ~ ., data = data1_aic)
explainer_rf2_aic <- explain(model_rf2_aic, data2_aic, apartmentsTest[6001:9000,1], label = "rf2_aic")
```

```{r, echo = FALSE, warning = FALSE}
mp_lm1 <- model_performance(explainer_lm1)
vi_lm1 <- variable_importance(explainer_lm1, type = "difference")

mp_rf1 <- model_performance(explainer_rf1)
vi_rf1 <- variable_importance(explainer_rf1, type = "difference")

mp_lm2_new <- model_performance(explainer_lm2_new)
vi_lm2_new <- variable_importance(explainer_lm2_new, type = "difference")

mp_lm2_all <- model_performance(explainer_lm2_all)
vi_lm2_all <- variable_importance(explainer_lm2_all, type = "difference")

mp_lm2_aic <- model_performance(explainer_lm2_aic)
vi_lm2_aic <- variable_importance(explainer_lm2_aic, type = "difference")

mp_rf2_new <- model_performance(explainer_rf2_new)
vi_rf2_new <- variable_importance(explainer_rf2_new, type = "difference")

mp_rf2_all <- model_performance(explainer_rf2_all)
vi_rf2_all <- variable_importance(explainer_rf2_all, type = "difference")

mp_rf2_aic <- model_performance(explainer_rf2_aic)
vi_rf2_aic <- variable_importance(explainer_rf2_aic, type = "difference")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
plot(mp_lm1, mp_rf1, mp_lm2_new, mp_lm2_all, mp_lm2_aic, mp_rf2_new, mp_rf2_all, mp_rf2_aic, geom = "boxplot")
```

```{r, echo = FALSE, fig.width=7, fig.height=6, warning = FALSE}
grid.arrange(
  plot(vi_lm1, vi_lm2_new, vi_lm2_all, vi_lm2_aic),
  plot(vi_rf1, vi_rf2_new, vi_rf2_all, vi_rf2_aic), ncol = 2)
```

```{r}
summary(model_lm1)
summary(model_lm2_aic)
```











