---
title: "SAFE examples - apartments dataset"
author: "Anna Gierlak"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(SAFE)
library(DALEX)
library(changepoint.np)
library(strucchange)
library(randomForest)
library(ggplot2)
library(utils)
library(stringr)
library(iml)
library(factorMerger)
```

Modele oparte na oryginalnych danych:

```{r, warning = FALSE}
model_lm1 <- lm(m2.price ~ ., data = apartments)
explainer_lm1 <- explain(model_lm1, data = apartmentsTest[1:3000,2:6], y = apartmentsTest[1:3000,1], label = "lm1")
set.seed(111)
model_rf1 <- randomForest(m2.price ~ ., data = apartments)
explainer_rf1 <- explain(model_rf1, data = apartmentsTest[1:3000,2:6], y = apartmentsTest[1:3000,1], label = "rf1")
```

**Transformacje (package=changepoint.np, type=constant):**

```{r, fig.width=6}
trans_prop <- transform_propositions(explainer_rf1, package = "changepoint.np", type = "constant", plot = TRUE, interactions = FALSE)
data1 <- transform_data(apartmentsTest[3001:6000,2:6], trans_prop, keep_old = FALSE)
data1_old <- transform_data(apartmentsTest[3001:6000,2:6], trans_prop, keep_old = TRUE)

data1 <- cbind(apartmentsTest[3001:6000,1], data1)
colnames(data1)[1] <- 'm2.price'
data1_old <- cbind(apartmentsTest[3001:6000,1], data1_old)
colnames(data1_old)[1] <- 'm2.price'
```

```{r, echo = FALSE}
knitr::kable(head(data1_old))
```

```{r}
data2 <- transform_data(apartmentsTest[6001:9000,2:6], trans_prop, keep_old = FALSE)
data2_old <- transform_data(apartmentsTest[6001:9000,2:6], trans_prop, keep_old = TRUE)

model_lm2 <- lm(m2.price ~ ., data = data1)
explainer_lm2 <- explain(model_lm2, data = data2, y = apartmentsTest[6001:9000,1], label = "lm2")

model_lm2_old <- lm(m2.price ~ ., data = data1_old)
explainer_lm2_old <- explain(model_lm2_old, data = data2_old, y = apartmentsTest[6001:9000,1], label = "lm2_old")

set.seed(111)
model_rf2 <- randomForest(m2.price ~ ., data = data1)
explainer_rf2 <- explain(model_rf2, data2, apartmentsTest[6001:9000,1], label = "rf2")

set.seed(111)
model_rf2_old <- randomForest(m2.price ~ ., data = data1_old)
explainer_rf2_old <- explain(model_rf2_old, data2_old, apartmentsTest[6001:9000,1], label = "rf2_old")
```

```{r, echo = FALSE, fig.width=7, fig.height=6}
mp_lm1 <- model_performance(explainer_lm1)
vi_lm1 <- variable_importance(explainer_lm1, type = "difference")

mp_rf1 <- model_performance(explainer_rf1)
vi_rf1 <- variable_importance(explainer_rf1, type = "difference")

mp_lm2 <- model_performance(explainer_lm2)
vi_lm2 <- variable_importance(explainer_lm2, type = "difference")

mp_lm2_old <- model_performance(explainer_lm2_old)
vi_lm2_old <- variable_importance(explainer_lm2_old, type = "difference")

mp_rf2 <- model_performance(explainer_rf2)
vi_rf2 <- variable_importance(explainer_rf2, type = "difference")

mp_rf2_old <- model_performance(explainer_rf2_old)
vi_rf2_old <- variable_importance(explainer_rf2_old, type = "difference")


plot(mp_lm1, mp_rf1, mp_lm2, mp_lm2_old, mp_rf2, mp_rf2_old, geom = "boxplot")
plot(vi_lm1, vi_rf1, vi_lm2, vi_lm2_old, vi_rf2, vi_rf2_old)
```

```{r}
summary(model_lm1)
summary(model_lm2)
```





**Transformacje (package=strucchange, type=constant):**

```{r, fig.width=6}
trans_prop <- transform_propositions(explainer_rf1, package = "strucchange", type = "constant", plot = TRUE, interactions = FALSE)
data1 <- transform_data(apartmentsTest[3001:6000,2:6], trans_prop, keep_old = FALSE)
data1_old <- transform_data(apartmentsTest[3001:6000,2:6], trans_prop, keep_old = TRUE)

data1 <- cbind(apartmentsTest[3001:6000,1], data1)
colnames(data1)[1] <- 'm2.price'
data1_old <- cbind(apartmentsTest[3001:6000,1], data1_old)
colnames(data1_old)[1] <- 'm2.price'
```

```{r, echo = FALSE}
knitr::kable(head(data1_old))
```

```{r}
data2 <- transform_data(apartmentsTest[6001:9000,2:6], trans_prop, keep_old = FALSE)
data2_old <- transform_data(apartmentsTest[6001:9000,2:6], trans_prop, keep_old = TRUE)


model_lm2 <- lm(m2.price ~ ., data = data1)
explainer_lm2 <- explain(model_lm2, data = data2, y = apartmentsTest[6001:9000,1], label = "lm2")

model_lm2_old <- lm(m2.price ~ ., data = data1_old)
explainer_lm2_old <- explain(model_lm2_old, data = data2_old, y = apartmentsTest[6001:9000,1], label = "lm2_old")

set.seed(111)
model_rf2 <- randomForest(m2.price ~ ., data = data1)
explainer_rf2 <- explain(model_rf2, data2, apartmentsTest[6001:9000,1], label = "rf2")

set.seed(111)
model_rf2_old <- randomForest(m2.price ~ ., data = data1_old)
explainer_rf2_old <- explain(model_rf2_old, data2_old, apartmentsTest[6001:9000,1], label = "rf2_old")
```

```{r, echo = FALSE, fig.width=7, fig.height=6}
mp_lm1 <- model_performance(explainer_lm1)
vi_lm1 <- variable_importance(explainer_lm1, type = "difference")

mp_rf1 <- model_performance(explainer_rf1)
vi_rf1 <- variable_importance(explainer_rf1, type = "difference")

mp_lm2 <- model_performance(explainer_lm2)
vi_lm2 <- variable_importance(explainer_lm2, type = "difference")

mp_lm2_old <- model_performance(explainer_lm2_old)
vi_lm2_old <- variable_importance(explainer_lm2_old, type = "difference")

mp_rf2 <- model_performance(explainer_rf2)
vi_rf2 <- variable_importance(explainer_rf2, type = "difference")

mp_rf2_old <- model_performance(explainer_rf2_old)
vi_rf2_old <- variable_importance(explainer_rf2_old, type = "difference")


plot(mp_lm1, mp_rf1, mp_lm2, mp_lm2_old, mp_rf2, mp_rf2_old, geom = "boxplot")
plot(vi_lm1, vi_rf1, vi_lm2, vi_lm2_old, vi_rf2, vi_rf2_old)
```

```{r}
summary(model_lm1)
summary(model_lm2)
```



**Transformacje (package=changepoint.np, type=linear):**

```{r, fig.width=6}
trans_prop <- transform_propositions(explainer_rf1, package = "changepoint.np", type = "linear", plot = TRUE, interactions = FALSE)
data1 <- transform_data(apartmentsTest[3001:6000,2:6], trans_prop, keep_old = FALSE)
data1_old <- transform_data(apartmentsTest[3001:6000,2:6], trans_prop, keep_old = TRUE)

data1 <- cbind(apartmentsTest[3001:6000,1], data1)
colnames(data1)[1] <- 'm2.price'
data1_old <- cbind(apartmentsTest[3001:6000,1], data1_old)
colnames(data1_old)[1] <- 'm2.price'
```

```{r, echo = FALSE}
knitr::kable(head(data1_old))
```

```{r}
data2 <- transform_data(apartmentsTest[6001:9000,2:6], trans_prop, keep_old = FALSE)
data2_old <- transform_data(apartmentsTest[6001:9000,2:6], trans_prop, keep_old = TRUE)

model_lm2 <- lm(m2.price ~ ., data = data1)
explainer_lm2 <- explain(model_lm2, data = data2, y = apartmentsTest[6001:9000,1], label = "lm2")

model_lm2_old <- lm(m2.price ~ ., data = data1_old)
explainer_lm2_old <- explain(model_lm2_old, data = data2_old, y = apartmentsTest[6001:9000,1], label = "lm2_old")

set.seed(111)
model_rf2 <- randomForest(m2.price ~ ., data = data1)
explainer_rf2 <- explain(model_rf2, data2, apartmentsTest[6001:9000,1], label = "rf2")

set.seed(111)
model_rf2_old <- randomForest(m2.price ~ ., data = data1_old)
explainer_rf2_old <- explain(model_rf2_old, data2_old, apartmentsTest[6001:9000,1], label = "rf2_old")
```

```{r, echo = FALSE, fig.width=7, fig.height=6}
mp_lm1 <- model_performance(explainer_lm1)
vi_lm1 <- variable_importance(explainer_lm1, type = "difference")

mp_rf1 <- model_performance(explainer_rf1)
vi_rf1 <- variable_importance(explainer_rf1, type = "difference")

mp_lm2 <- model_performance(explainer_lm2)
vi_lm2 <- variable_importance(explainer_lm2, type = "difference")

mp_lm2_old <- model_performance(explainer_lm2_old)
vi_lm2_old <- variable_importance(explainer_lm2_old, type = "difference")

mp_rf2 <- model_performance(explainer_rf2)
vi_rf2 <- variable_importance(explainer_rf2, type = "difference")

mp_rf2_old <- model_performance(explainer_rf2_old)
vi_rf2_old <- variable_importance(explainer_rf2_old, type = "difference")


plot(mp_lm1, mp_rf1, mp_lm2, mp_lm2_old, mp_rf2, mp_rf2_old, geom = "boxplot")
plot(vi_lm1, vi_rf1, vi_lm2, vi_lm2_old, vi_rf2, vi_rf2_old)
```

```{r}
summary(model_lm1)
summary(model_lm2)
```





**Transformacje (package=strucchange, type=linear):**

```{r, fig.width=6}
trans_prop <- transform_propositions(explainer_rf1, package = "strucchange", type = "linear", plot = TRUE, interactions = FALSE)
data1 <- transform_data(apartmentsTest[3001:6000,2:6], trans_prop, keep_old = FALSE)
data1_old <- transform_data(apartmentsTest[3001:6000,2:6], trans_prop, keep_old = TRUE)

data1 <- cbind(apartmentsTest[3001:6000,1], data1)
colnames(data1)[1] <- 'm2.price'
data1_old <- cbind(apartmentsTest[3001:6000,1], data1_old)
colnames(data1_old)[1] <- 'm2.price'
```

```{r, echo = FALSE}
knitr::kable(head(data1_old))
```

```{r}
data2 <- transform_data(apartmentsTest[6001:9000,2:6], trans_prop, keep_old = FALSE)
data2_old <- transform_data(apartmentsTest[6001:9000,2:6], trans_prop, keep_old = TRUE)

model_lm2 <- lm(m2.price ~ ., data = data1)
explainer_lm2 <- explain(model_lm2, data = data2, y = apartmentsTest[6001:9000,1], label = "lm2")

model_lm2_old <- lm(m2.price ~ ., data = data1_old)
explainer_lm2_old <- explain(model_lm2_old, data = data2_old, y = apartmentsTest[6001:9000,1], label = "lm2_old")

set.seed(111)
model_rf2 <- randomForest(m2.price ~ ., data = data1)
explainer_rf2 <- explain(model_rf2, data2, apartmentsTest[6001:9000,1], label = "rf2")

set.seed(111)
model_rf2_old <- randomForest(m2.price ~ ., data = data1_old)
explainer_rf2_old <- explain(model_rf2_old, data2_old, apartmentsTest[6001:9000,1], label = "rf2_old")
```

```{r, echo = FALSE, fig.width=7, fig.height=6}
mp_lm1 <- model_performance(explainer_lm1)
vi_lm1 <- variable_importance(explainer_lm1, type = "difference")

mp_rf1 <- model_performance(explainer_rf1)
vi_rf1 <- variable_importance(explainer_rf1, type = "difference")

mp_lm2 <- model_performance(explainer_lm2)
vi_lm2 <- variable_importance(explainer_lm2, type = "difference")

mp_lm2_old <- model_performance(explainer_lm2_old)
vi_lm2_old <- variable_importance(explainer_lm2_old, type = "difference")

mp_rf2 <- model_performance(explainer_rf2)
vi_rf2 <- variable_importance(explainer_rf2, type = "difference")

mp_rf2_old <- model_performance(explainer_rf2_old)
vi_rf2_old <- variable_importance(explainer_rf2_old, type = "difference")


plot(mp_lm1, mp_rf1, mp_lm2, mp_lm2_old, mp_rf2, mp_rf2_old, geom = "boxplot")
plot(vi_lm1, vi_rf1, vi_lm2, vi_lm2_old, vi_rf2, vi_rf2_old)
```

```{r}
summary(model_lm1)
summary(model_lm2)
```











